### PR TITLE
Added `fn from_texture_rect` to accomodate sprite creation from a Sou…

### PR DESCRIPTION
**Pull request by BedfordWest**
…rceRectangle

Addresses [Add clipping window to sprite #116](https://github.com/PistonDevelopers/sprite/issues/116)

This is my initial swing at implementing this solution, as I really wanted a way to go directly through the Sprite library to create Sprites from a source rectangle without creating additional textures in memory.

I tested this with the existing Sprite example to verify I didn't cause any regression with existing methods, and then I tried modifying the example to use a portion of the sprite to verify it can pull sub-regions and display them correctly.

It seems to work alright, but I'm still fairly new to both Rust and Piston, so I'd certainly appreciate review/improvement/suggestion! I'm happy to work on implementing any suggestions necessary, but I'd also appreciate getting this merged sooner rather than later so my own projects can pull from the actual library rather than my local copy! (:

### CODE REVIEW

**Comment by BedfordWest** [comment]
I guess there's room to debate whether or not the `from_texture_rect` initializer is actually necessary. I realized one could just as easily initialize with `from_texture` and then use `set_src_rect` when setting the clipping rectangle. It's a decent amount of boilerplate for small utility. I'll leave in for now, but I'm curious what others think.

**Comment by bvssvni** [comment]
Looks good! I think having a constructor for this is fine.

Merging.

**Comment by BedfordWest** [comment]
Thanks for the quick review!

**Comment by bvssvni** [comment]
👍 Keep up the good work!

**Pull request merged**
