### PR TITLE
Removed `State` suffix on `AnimationState` variants

### PR DESCRIPTION
**Pull request by bvssvni**
Closes https://github.com/PistonDevelopers/sprite/issues/102

### CODE REVIEW

**Comment by sinistersnare** [comment]
Is there a reason that we need an issue and a whole PR for each little thing? The whole point of Pull requests is that they can be discussed and then merged as a team, but if we are just going to merge things without consensus, why dont we just merge straight into master?

**Comment by bvssvni** [comment]
@sinistersnare The reason to use a separated issue from the PR is to keep the discussion of planning and implementation separate. The Piston project encourages self-merging under the assumption that you know what you are doing, see https://github.com/PistonDevelopers/piston/issues/674. This saves time. We don't merge straight into master because it makes it harder for people to follow the changes. Work-in-progress PRs are different. Also, see https://github.com/PistonDevelopers/piston/issues/835 for how to start a discussion. Don't interrupt people by posting on PRs unless you have something to say specifically about that PR.

**Comment by sinistersnare** [comment]
Work in progress PRs I agree with, the generate discussion. Discussion in PRs/Issues I agree with, consensus needs to be reached. This PR, for example, is neither of those, it was a unilateral decision (which I am perfectly fine with). 

Its really just aggravating getting dozens of emails a day from the dozens of issues that are opened and closed immediately and PRs that are submitted and merged immediately. I think that if discussion is warranted, then a PR is a good idea, and otherwise there is no point. No discussion needs to be had on the implementation on removing the `State` suffix, just a PR will do. Its just a duplication of work that is completely unnecessary in most cases.

**Comment by bvssvni** [comment]
@sinistersnare We need issues to track changes over time. You can unsubscribe from the repos that fills your inbox, then resubscribe when things settle down.

**Pull request merged**
