### PR TITLE
Add an accessor for a scene's children.

### PR DESCRIPTION
**Pull request by xaviershay**
I am using this for experimentation with alternate drawing algorithms,
such as adding clipping, but seems likely to be other uses.

### CODE REVIEW

**Comment by bvssvni** [comment]
Notice that you also can use `&[Sprite<I>]`.

**Comment by xaviershay** [comment]
Is that just a syntax shortcut (not sure how to google it)? Or is it semantically different?

**Comment by bvssvni** [comment]
The difference is that `&[Sprite<I>]` returns an immutable slice, which is a fat pointer, because it contains the length in addition to the pointer.

Don't think there is a benefit over returning `&Vec<Sprite<I>>`, though, unless there is a chance the internal representation changes from `Vec` to something else.

**Comment by xaviershay** [comment]
cool, thanks for detail!

**Pull request merged**
